### ISSUE TITLE
TODO: Before mod release

### ISSUE THREAD

**Issue by lumiscosity** [lumiscosity/lumirefiner#1]
- [ ] Finish textures for items
- [ ] Finish textures for blocks
- [ ] Implement loot tables
- [ ] Move refiner to a new class
    - [ ] Add the functions to the refiner
    - [ ] Implement the refiner recipe type
- [ ] Modify vanilla loot tables for block drops (for damond/emerald clumps) and to put unrefined ingots in chests
    - [ ] Modify some mod loot tables as well
